// This file is automatically generated for the latest release using the `internal_update_targets` feature

use crate::Target;

/// Release tag the prebuilt binaries are downloaded from.
pub const RELEASE_TAG: &str = "2026.09.11+087be1c.1";

/// Every archive this crate can download, for [`RELEASE_TAG`].
pub const AVAILABLE_TARGETS: &[Target] = &[
    Target {
        name: "aarch64-linux-gnu",
        static_crt: true,
        sha256: "73db50a1315f51458cd80015e49147a424637f95a11c0ff1820c9999e8ff2fbd",
    },
    Target {
        name: "aarch64-linux-musl",
        static_crt: true,
        sha256: "689d95a60c4cb17d64bb75b34faa65712fad20523d9e82ca3aa35cc25c5b5555",
    },
    Target {
        name: "aarch64-macos-none",
        static_crt: true,
        sha256: "03cd4665c693267a85924f1ffd9f85629dc5668f5f39dc7bbc725595a0615adc",
    },
    Target {
        name: "aarch64-windows-gnu",
        static_crt: true,
        sha256: "1f3adf09facf1dc5db0db55919e69953def1c2e2effc257620b0b7ee584035a8",
    },
    Target {
        name: "x86_64-linux-gnu",
        static_crt: true,
        sha256: "863c29363e016f413d2df66c786063cb4fe04905e474dfdd6a86c68fe3bfa982",
    },
    Target {
        name: "x86_64-linux-musl",
        static_crt: true,
        sha256: "b0127fcfb0023489f6d1bff38135780da995a54b06e3afb1a4be5d1b34cec965",
    },
    Target {
        name: "x86_64-macos-none",
        static_crt: true,
        sha256: "cbb9585bc9cfa8ef746bcd496d769bb36cb6e0d5291200affd71edc23f0d6881",
    },
    Target {
        name: "x86_64-windows-gnu",
        static_crt: true,
        sha256: "86399396eb7538aa74c980b4c045e288729ea74f72662629adde0e605a676419",
    },
    Target {
        name: "x86_64-windows-msvc",
        static_crt: true,
        sha256: "f5322f221b5c19c36d2ce6af7bf44bb236969b2284254807262ef07b80a81d4b",
    },
    Target {
        name: "x86_64-windows-msvc",
        static_crt: false,
        sha256: "3c0d35d55fe3e7b3b288b80b0fd1bcd416598da422ac34ea44194bac7842a513",
    },
];
