// This file is automatically generated for the latest release using the `internal_update_targets` feature

use crate::Target;

/// Release tag the prebuilt binaries are downloaded from.
pub const RELEASE_TAG: &str = "2026.09.13+c831d94.1";

/// Every archive this crate can download, for [`RELEASE_TAG`].
pub const AVAILABLE_TARGETS: &[Target] = &[
    Target {
        name: "aarch64-linux-gnu",
        static_crt: true,
        sha256: "48f57d7ec8e9fa8edf8ca6925207dd463badde3f62c261971fa6da462e708051",
    },
    Target {
        name: "aarch64-linux-musl",
        static_crt: true,
        sha256: "e86c52f3cbf77f42f810f71de6f54e0bf4cf702174c3498b5ca95774f089d6a7",
    },
    Target {
        name: "aarch64-macos-none",
        static_crt: true,
        sha256: "cea3bcb42e58761500f0d65bde680b1fa2390ae73d98faa5d7c0cdd6645a6543",
    },
    Target {
        name: "aarch64-windows-gnu",
        static_crt: true,
        sha256: "dd97762768cf744f93ba0c72ce16fa866d860ac54b4efca7fe9fbf143675b663",
    },
    Target {
        name: "x86_64-linux-gnu",
        static_crt: true,
        sha256: "e145fe00597022ba95357c8f8391f8aaf918950275da3039057064595b42e8be",
    },
    Target {
        name: "x86_64-linux-musl",
        static_crt: true,
        sha256: "63173f8557dd450e32535141a869be16dfef6e5f887cbdae63c09e6d719472ee",
    },
    Target {
        name: "x86_64-macos-none",
        static_crt: true,
        sha256: "a45f383998ac8df219b5f4ea4c1a0a78bb03b20de03f93b35c070caf57faab50",
    },
    Target {
        name: "x86_64-windows-gnu",
        static_crt: true,
        sha256: "4fd00aa47607a53a38c1fbabab0934053520b7e17c1430fe306e01735d4af58e",
    },
    Target {
        name: "x86_64-windows-msvc",
        static_crt: true,
        sha256: "2cb66262af27b66cb14f4c5cd3e97c3736d072db24d70b3c5b4ddc5e05a1ec29",
    },
    Target {
        name: "x86_64-windows-msvc",
        static_crt: false,
        sha256: "6c03f39c8fd6fed5e860ad1675e9c52a3812ad550ccb04b743314d4a226b2ba8",
    },
];
